title: "Wassim Beltaief"
description: "A personal page about projects, articles and contact"
about: "I'm a passionate, solution orientated software engineer with focus on Android development"
location: "Hamburg, Germany"
email: beltaief.wassim@gmail.com
baseurl: ""
url: "http://wassim-beltaief.com"
twitter_username: wassim_ltaief
github_username:  wassimbenltaief
image: "./images/profile.jpg"

# google analytics tracking code, please change the value
# g_analytics: "UA-72004048-3"

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "Imprint"
name_badge: "Ein Artikel von"
rss_badge: "Subscribe to feed !"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
